# Railway configuration for RAG application
# Deploy backend service only

[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10