# Railway configuration for RAG application
# Deploy using Docker Compose

[build]
builder = "dockercompose"
dockercomposePath = "server/docker-compose.yml"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10